apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: sender
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        run: sender
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1beta1
      kind: KafkaChannel
      name: kafka-channel
